config/routes.rb
::Refinery::Application.routes.draw do
  resources :speakers, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :speakers, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  has_and_belongs_to_many :events

  acts_as_indexed :fields => [:firstname, :lastname, :description]

  validates :firstname, :presence => true

  belongs_to :image

  def to_s
    [ firstname , lastname ] * ' '
  end

end

app/controllers/admin/speakers_controller.rb
module Admin
  class SpeakersController < Admin::BaseController

    crudify :speaker, :xhr_paging => true

  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController

  before_filter :find_all_speakers
  before_filter :find_page

  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @speaker in the line below:
    present(@page)
  end

  def show
    @speaker = Speaker.find(params[:id])

    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @speaker in the line below:
    present(@page)
  end

protected

  def find_all_speakers
    @speakers = Speaker.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/speakers").first
  end

end

app/views/admin/speakers/_actions.html.erb
<ul>
  <% if Admin::SpeakersController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_speakers_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_speaker_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::SpeakersController.sortable? and Speaker.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Speakers"),
                 admin_speakers_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Speakers"),
                 admin_speakers_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/speakers/_form.html.erb
<%= form_for [:admin, @speaker] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @speaker,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :firstname -%>
    <%= f.text_field :firstname, :class => 'larger widest'  -%>
  </div>
  
  <div class='field'>
    <%= f.label :lastname -%>
    <%= f.text_field :lastname  -%>
  </div>
  
  <div class='field'>
    <%= f.label :image -%>
    <%= render :partial => "/shared/admin/image_picker", :locals => {
          :f => f,
          :field => :image_id,
          :image => @speaker.image,
          :toggle_image_display => false
        } %>
  </div>
  
  <div class='field'>
    <div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
      <ul id='page_parts'>
        <% [:description].each_with_index do |part, part_index| %>
          <li class='ui-state-default<%= ' ui-state-active' if part_index == 0 %>'>
            <%= link_to part.to_s.titleize, "##{part}" %>
          </li>
        <% end %>
      </ul>

      <div id='page_part_editors'>
        <% [:description].each do |part| %>
          <div class='page_part' id='<%= part %>'>
            <%= f.text_area part, :rows => 20, :class => 'wymeditor widest' -%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.speakers.speaker'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @speaker.firstname)
              } %>
<% end -%>
<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      page_options.init(false, '', '');
    });
  </script>
<% end %>

app/views/admin/speakers/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @speakers.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'speakers' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/speakers/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'speaker', :collection => @speakers %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/speakers/_speaker.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(speaker) -%>">
  <span class='title'>
    <%= speaker.firstname %> <%= speaker.lastname %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), speaker_path(speaker),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_speaker_path(speaker),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_speaker_path(speaker),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => speaker.firstname),
        :method => :delete %>
  </span>
</li>

app/views/admin/speakers/_speakers.html.erb
<%= will_paginate @speakers %>
<%= render :partial => "sortable_list" %>

app/views/admin/speakers/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/speakers/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::SpeakersController.sortable? and Speaker.count > 1 %>

app/views/admin/speakers/new.html.erb
<%= render :partial => "form" %>

app/views/events/_list.erb
<ul class="events">
  <% events.each do |e| %>
    <li>
      <%= link_to e.title, event_path(e) %>
    </li>
  <% end %>
</ul>  

app/views/events/_list.html.erb
<ul class="events">
  <% events.each do |e| %>
    <li>
      <%= link_to e.title, event_path(e) %>
    </li>
  <% end %>
</ul>  

app/views/speakers/_list.html.erb
<%
  with_images ||= false
  img_width   ||= 50
  img_height  ||= img_width
%>

<ul class="speakers <%=  with_images ? 'with_images' : 'without_images' %>">
  <% speakers.each do |speaker| %>
    <li>
      <%= link_to speaker, :style => "width: #{img_width.to_i}px; height: #{img_height.to_i+40}px" do %>

        <% if with_images %>
            <section class="speaker_image image-nofx">
            <% if (image=speaker.image).present? %>
            	<%= image_fu image, "#{img_width}x#{img_height}#c" %>
            <% else %>
              <%= image_tag('silhouette_50.png', :size =>  "#{img_width}x#{img_height}") %>
            <% end %>
            </section>
        <% end %>

        <%= speaker %>
      <% end %>

    </li>
  <% end %>
</ul>

app/views/speakers/_speaker.html.erb
<%
	individual ||= false
	speaker_class = individual ?  :individual : :listed
-%>

<%= div_for speaker, :class => speaker_class  do -%>



  <% content_for :stylesheets do %>
    <%= stylesheet_link_tag 'refinerycms-speakers' %>
  <% end %>

  <% if individual %>

    <h2>
      <%= speaker.firstname %> <%= speaker.lastname %>
    </h2>

    <% if (image=speaker.image).present? %>
      <section class="speaker_image">
        <p>
      	<%= image_fu image, "150x150#c", :class => 'image-nofx' %>
        </p>
      </section>
    <% end %>

    <% if (description=speaker.description).present? %>
      <section>
        <%# <h3><%= t('.description') % ></h3> %>
        <%=raw description %>
      </section>
    <% end %>

    <% if (events=speaker.events).any? %>
      <section>
        <h3><%= t('.events')  %> avec <%= speaker.firstname %> <%= speaker.lastname %></h3>
        <%= render 'events/list', :events => events %>
      </section>
    <% end %>







  <% else %>

    <a href="<%= speaker_path(speaker) %>">
      <%= speaker.firstname %>
      <%= speaker.lastname %>
    </a>

  <% end %>
<% end %>  

app/views/speakers/index.html.erb
<% content_for :body_content_left do %>
  <%= render 'speakers/list', :speakers => @speakers %>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/speakers/show.html.erb
<% content_for :body_content_title do %>
  <%= @speaker.firstname %>   <%= @speaker.lastname %>
<% end %>

<% content_for :body_content_left do %>
  <%= render @speaker, :individual => true %>
<% end %>

<% content_for :body_content_right do %>
  <aside>
    <h2><%= t('.other') %></h2>
    <%= render 'speakers/list', :speakers => @speakers, :with_images => true, :img_width => 30  %>
  </aside>
<% end %>

<%= render :partial => "/shared/content_page" %>